https:
  host: "0.0.0.0"
  port: "8082"
  
diwali:
  date: "![MD65B3biBP8qKMJahYIe6Q==]"
  cloth: "![DA7VN2SYh//G8VF6Xfgbww==]"
  home: "![8Y1V+XV/8WSv6lJlulrdiMhbNO6RYJ4Xz+uFhE4YOoa3EIHAMSjru5DkP6G+JC25]"